## -------------------- Spring Configurations
spring:
  jpa:
    generate-ddl: true
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2

  dataSource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

## -------------------- Server Configurations
server:
  servlet:
    context-path: /employee-management
  compression:
    enabled: true
  port: 9090
